version: "3.9"
services:
  dev:
    # build:
    #   context: .
    # working_dir: /home/usr/code
    image: jupyter/minimal-notebook
    volumes:
      - type: bind
        source: ..
        target: /home/usr/code
        consistency: delegated
    networks:
      - mynetwork

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    environment:
      - "discovery.type=single-node"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ENROLLMENT_TOKEN=${ENROLLMENT_TOKEN}
    ports:
      - "9200:9200"
    networks:
      - mynetwork
  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    environment:
      - "discovery.type=single-node"
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
      - ENROLLMENT_TOKEN=${ENROLLMENT_TOKEN}

    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
